debug: true

spring:
  http:
    encoding:
      charset: utf-8
  messages:
    basename: i18n/core/messages,i18n/biz/messages
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: com.coding.commons.base.data.jpa.CustomImplicitNamingStrategy
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.dialect: com.coding.commons.base.data.jpa.CustomPostgreSQLDialect
  jta:
    enabled: true
    transaction-manager-id: service-admin
    atomikos:
      properties:
        service: com.atomikos.icatch.standalone.UserTransactionServiceFactory
        max-actives: 200
        enable-logging: true
      datasource:
        base:
          unique-resource-name: baseDataSource
          max-pool-size: 5
          min-pool-size: 1
          max-life-time: 20000
          borrow-connection-timeout: 10000
          xa-data-source-class-name: org.postgresql.xa.PGXADataSource
          xa-properties:
            user: supermarket
            password: supermarket
            url: jdbc:postgresql://127.0.0.1:5432/supermarket-base
        product:
          unique-resource-name: productDataSource
          max-pool-size: 5
          min-pool-size: 1
          max-life-time: 20000
          borrow-connection-timeout: 10000
          xa-data-source-class-name: org.postgresql.xa.PGXADataSource
          xa-properties:
            user: supermarket
            password: supermarket
            url: jdbc:postgresql://127.0.0.1:5432/supermarket-product
        order:
          unique-resource-name: orderDataSource
          max-pool-size: 5
          min-pool-size: 1
          max-life-time: 20000
          borrow-connection-timeout: 10000
          xa-data-source-class-name: org.postgresql.xa.PGXADataSource
          xa-properties:
            user: supermarket
            password: supermarket
            url: jdbc:postgresql://127.0.0.1:5432/supermarket-order
        coupon:
          unique-resource-name: couponDataSource
          max-pool-size: 5
          min-pool-size: 1
          max-life-time: 20000
          borrow-connection-timeout: 10000
          xa-data-source-class-name: org.postgresql.xa.PGXADataSource
          xa-properties:
            user: supermarket
            password: supermarket
            url: jdbc:postgresql://127.0.0.1:5432/supermarket-coupon
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

swagger:
  enabled: true
  title: service-admin
  description: service-admin
  base-package: com.coding.supermarket.serviceadmin.controller

management:
  endpoints:
    web:
      exposure:
        include: ["*"]
  endpoint:
    shutdown:
      enabled: true

sample:
  string:
    property: Client App
  int:
    property: 2
