server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  server:
    eviction-interval-timer-in-ms: 60000
    wait-time-in-ms-when-sync-empty: 0
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
