debug: true
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/supermarket
    username: supermarket
    password: supermarket
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: com.coding.commons.base.data.jpa.CustomImplicitNamingStrategy
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.dialect: com.coding.commons.base.data.jpa.CustomPostgreSQLDialect
    show-sql: true
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
