MYSQL_HOST: 127.0.0.1
MYSQL_PORT: 3306
MYSQL_DB: supermarket
MYSQL_USER: root
MYSQL_PASSWORD: 123456

spring:
  cloud:
    nacos:
      discovery:
        register-enabled: true
        server-addr: 127.0.0.1:8848
